title: Koding
email: support@koding.com
repository: sinan/koding
description: >
  Instantly share, scale and manage integrated development
  environments in a cloud IDE.
keywords: >
  integrated development environment, cloud ide, dev environment,
  cloud development environment, cloud editor, virtual dev environment,
  web based ide, test environment, docker, aws, vagrant, azure, rackspace
baseurl: ""
# baseurl: "/koding"
url: "http://dev.koding.com:4000"
# url: "https://sinan.github.io"
# production_url: "https://sinan.github.io/koding"
paginate_path: "/blog/page:num/"
paginate: 5
timezone: America/Los_Angeles
exclude:
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- vendor/bundle
gems:
- jekyll-paginate
sass:
  style: compressed
  sass_dir: _css
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
social:
  twitter: https://twitter.com/koding
  github:  https://github.com/koding
  facebook:  https://facebook.com/koding
  linkedin:  https://linkedin.com/company/koding

